In [30]:
import numpy as np 
import pandas as pd 
import re

In [31]:
# read the dataset from exel sheet
df = pd.read_csv('DatasetNLP.csv')
# show sample of data set and shape
df.head()

title                              author  \
0     كتاب لغز المنزل رقم في                   الكاتب محمود سالم   
1  كتاب لغز الموسيقار الصغير                   الكاتب محمود سالم   
2    كتاب لغز الوثائق السرية                   الكاتب محمود سالم   
3             كتاب لا تتجاهل  الكاتب هارون يحيىالكاتب هارون يحيى   
4   كتاب الحياة في سبيل الله  الكاتب هارون يحيىالكاتب هارون يحيى   

                                           book_link  \
0  https://www.arab-books.com/books/%d9%83%d8%aa%...   
1  https://www.arab-books.com/books/%d9%83%d8%aa%...   
2  https://www.arab-books.com/books/%d9%83%d8%aa%...   
3  https://www.arab-books.com/books/%d9%83%d8%aa%...   
4  https://www.arab-books.com/books/%d9%83%d8%aa%...   

                                         BookSummary PublishingHouse  \
0  “وانطلق الجميع إلى شارع النيل. كان صباحًا مشرق...    مؤسسة هنداوي   
1  وتابعت نوسة قائلة: الأسبوع الماضي اختطفت العصا...    مؤسسة هنداوي   
2  عندما استيقظ تختخ في اليوم التالي ، كانت تنتظر...    مؤسسة هنداوي   
3  كتاب لا تتجاهل للكاتب هارون يحيى: منذ اللحظة ا...    عدنان أوكطار   
4  كتاب الحياة في سبيل الله للكاتب هارون يحيى: يج...    عدنان أوكطار   

       TypeOfBook  
0  روايات بوليسية  
1  روايات بوليسية  
2  روايات بوليسية  
3    الأدب العربي  
4         اسلامية

In [32]:
# ----------- preprocessing section -----------#
# 1- handle null value 
df['TypeOfBook'].fillna(value="مجهول",inplace=True)
df['author'].fillna(value="مجهول",inplace=True)
df['PublishingHouse'].fillna(value="مجهول",inplace=True)
df['BookSummary'].fillna(value=" ",inplace=True)


In [33]:
# check if the data set contains null or not 
df.isnull().sum()

title              0
author             0
book_link          0
BookSummary        0
PublishingHouse    0
TypeOfBook         0
dtype: int64

In [34]:
for i in range(len(df['title'])):
    df['title'][i] = re.sub('كتاب','',df['title'][i])
    df['author'][i]= re.sub('الكاتب','',df['author'][i])
    df['TypeOfBook'][i]= df['TypeOfBook'][i].rstrip()
    df['TypeOfBook'][i]= re.sub('^ ','',df['TypeOfBook'][i])

In [35]:
df['TypeOfBook'].unique()

array(['روايات بوليسية', 'الأدب العربي', 'اسلامية', 'مجهول',
       'الفلسفة والمنطق', 'الأدب', 'علوم اللغة', 'العقيدة',
       'الأدب اللغة العربية', 'متنوعة', 'أعلام وشخصيات', 'اللغة العربية',
       'قصص أطفال', 'العلوم السياسية والاستراتيجية', 'الأطفال',
       'القصص القصيرة المترجمة', 'الروايات العالمية المترجمة',
       'الثقافة العامة', 'أصول الفقه', 'التاريخ', 'السياسة',
       'الخيال العلمي', 'علم النفس', 'روايات عربية', 'تطوير الذات',
       'طبية', 'أدب السجون', 'التاريخ القديم', 'الأدب الثقافة العامة',
       'البرمجة والتصاميم', ' العقيدة', 'التاريخ الحديث', 'أساطير',
       ' روايات بوليسية', 'التنمية الذاتية', 'العلوم الإنسانية', 'تفاسير',
       'الجغرافيا', 'علوم القرآن الكريم والسنة النبوية', 'السيرة النبوية',
       'فقه المرأة المسلمة', 'الحديث', 'النحو والصرف', 'النقد والبلاغة',
       'أدب الرحلات', 'إدارة الأعمال', 'رمضانيات', 'الرياضيات',
       'البرمجة والتصاميم الثقافة العامة ما وراء الطبيعة', 'الأحياء الطب',
       'الفن', 'الثقافة العامة ما وراء الطبيعة',

In [36]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.isri import ISRIStemmer
import re # Regular expression library
import string
def remove_stop_words(tokens):
    result_tokens =[]
    stopwords_list = stopwords.words('arabic')
    for token in tokens:
        if token not in stopwords_list:
            result_tokens.append(token)
    return result_tokens
# make stemming for arabic word using IRIStemmer
def stemming(tokens):
    st = ISRIStemmer()
    result_tokens=[]
    for token in tokens:
        result_tokens.append(st.stem(token))
    return result_tokens
for i in range(len(df['BookSummary'])):
    # Remove Punctuation from text
    df['BookSummary'][i] = re.sub('[%s]' % re.escape(string.punctuation), '', str(df['BookSummary'][i]))
    df['BookSummary'][i] = re.sub('،','',df['BookSummary'][i])
    # Remove any digit number from text 
    df['BookSummary'][i] = re.sub('\d+','',df['BookSummary'][i])
    df['BookSummary'][i] = re.sub('PDF','',df['BookSummary'][i])
    # convert text to tokinze 
    tokens =word_tokenize(str(df['BookSummary'][i]))
    tokens_title= word_tokenize(str(df['title'][i]))
    # Remove Stop word from text 
    process_Tokens = remove_stop_words(tokens)
    process_Tokens_title = remove_stop_words(tokens_title)
    stemming_Tokens =stemming(process_Tokens)
    stemming_Tokens_title=stemming(process_Tokens_title)
    
    # convert tokens to one text 
    df['BookSummary'][i] =' '.join(stemming_Tokens)
    df['title'][i]=' '.join(stemming_Tokens_title)
print(df['BookSummary'][5])

كتب عظم كان كتب هار يحى قصى انس عجب عمل جهز جسم بحث حقق مجر سمو تبع اثر حيء طبع ضؤل حجم صعب رؤت سال كيف تحر شيء كون وجد حتم نظا كامل دهش ثير عنصر نطق أدل عظم وهي بلا شك عظم الل خلق شيء نبع ايت جمل بدع وجد تبر الل احس خلق كتب عظم كان
عظم كان


In [37]:
# features not needed 
df.drop(['book_link'],axis=1,inplace=True)
df.head()

title                  author  \
0      لغز نزل رقم              محمود سالم   
1  لغز موسيقار صغر              محمود سالم   
2      لغز وثق سرة              محمود سالم   
3              جهل   هارون يحيى هارون يحيى   
4      حية سبل الل   هارون يحيى هارون يحيى   

                                         BookSummary PublishingHouse  \
0  “ طلق جمع شرع نيل صبح شرق وسر طول كورنيش جمل و...    مؤسسة هنداوي   
1  تبع نوس قئل سبع اضي خطف عصب طفل اخر نفس طرق مر...    مؤسسة هنداوي   
2  عند يقظ ختخ اليوم تلي كانت نظر فجأ جدد تصل فتش...    مؤسسة هنداوي   
3  كتب جهل كتب هار يحى لحظ يقظ انس صبح غمس شغل نه...    عدنان أوكطار   
4  كتب حية سبل الل كتب هار يحى جهد انس حية حصل كس...    عدنان أوكطار   

       TypeOfBook  
0  روايات بوليسية  
1  روايات بوليسية  
2  روايات بوليسية  
3    الأدب العربي  
4         اسلامية

In [38]:
# -------make label encoder --------------#
from sklearn.preprocessing import LabelEncoder
encode_x = LabelEncoder()
df['TypeOfBook'] = encode_x.fit_transform(df['TypeOfBook'])
df['author'] =encode_x.fit_transform(df['author'])
df['PublishingHouse']=encode_x.fit_transform(df['PublishingHouse'])
df.head()

title  author                                        BookSummary  \
0      لغز نزل رقم      79  “ طلق جمع شرع نيل صبح شرق وسر طول كورنيش جمل و...   
1  لغز موسيقار صغر      79  تبع نوس قئل سبع اضي خطف عصب طفل اخر نفس طرق مر...   
2      لغز وثق سرة      79  عند يقظ ختخ اليوم تلي كانت نظر فجأ جدد تصل فتش...   
3              جهل      85  كتب جهل كتب هار يحى لحظ يقظ انس صبح غمس شغل نه...   
4      حية سبل الل      85  كتب حية سبل الل كتب هار يحى جهد انس حية حصل كس...   

   PublishingHouse  TypeOfBook  
0              506          92  
1              506          92  
2              506          92  
3              467          29  
4              467          21

In [39]:
# features variables
x = df[['title','author','BookSummary','PublishingHouse']]
# target variables
y = df['TypeOfBook']

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np 
import scipy as sp
from scipy.sparse import coo_matrix, hstack


# ------------ extract features -----------#
train_title_vectorizer = TfidfVectorizer()
train_BookSummary_vectorizer = TfidfVectorizer()

train_title_features = train_title_vectorizer.fit_transform(x['title'])
train_BookSummary = train_BookSummary_vectorizer.fit_transform(x['BookSummary'])

x=hstack((np.array(x['author'])[:,None],
          np.array(x['PublishingHouse'])[:,None],
          train_BookSummary,train_title_features))

print(x.shape)

(6428, 14434)


In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=0)

In [42]:
# ----------randomForest model -------------#
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=1000, random_state=11)
classifier.fit(x_train, y_train) 
from sklearn import metrics 
predictions = classifier.predict(x_test)
print(metrics.confusion_matrix(y_test,predictions))
print(metrics.classification_report(y_test,predictions))
print(metrics.accuracy_score(y_test,predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 5 0 0]
 ...
 [0 0 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00        17
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         6
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00        24
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         0
          14       0.00      0.00      0.00        13
          15       0.00      0.00      0.00         0
          16       0.00      0.00      0.00         3
          17       0.00      0.00      0.00        14
          18   

C:\Users\mahmoud0020\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mahmoud0020\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [44]:
# ----------- logistic regression model -----------#
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(solver='lbfgs',max_iter=1000)
lr_model.fit(x_train,y_train)
predictions = lr_model.predict(x_test)
from sklearn import metrics 
print(metrics.confusion_matrix(y_test,predictions))
print(metrics.classification_report(y_test,predictions))
print(metrics.accuracy_score(y_test,predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           2       0.00      0.00      0.00        17
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         0
           8       0.00      0.00      0.00        24
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         0
          14       0.00      0.00      0.00        13
          16       0.00      0.00      0.00         3
          17       0.00      0.00      0.00        14
          18       0.00      0.00      0.00         5
          20       0.00      0.00      0.00         5
          21       0.31      0.98      0.47       593
          22       0.00      0.00      0.00         1
          24   

C:\Users\mahmoud0020\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\mahmoud0020\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\mahmoud0020\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being 